version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        image: nginx
        ports:
            - 8098:80
        links:
            - fpm
        volumes:
            - ./:/var/www/snovio.test
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/snovio.test
        links:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - 33060:3306
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
        volumes:
          - ./mysql:/var/lib/mysql